"""initial schema

Revision ID: 3f575448b862
Revises: 
Create Date: 2026-09-21 12:24:34.019050
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '3f575448b862'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('kaspi_product_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('merchant_id', 'sku', name=op.f('uq_products_merchant_id_sku'))
    )
    op.create_index(op.f('ix_products_kaspi_product_id'), 'products', ['kaspi_product_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.String(length=16), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('strategy_used', sa.Enum('beat_first', 'match_first', 'follow_second', 'target_position', 'fixed_price', 'manual', name='pricing_strategy', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.Enum('strategy_target', 'capped_at_max', 'fallback_position', 'pinned_to_min', 'no_competitors', 'fixed_price', name='decision_reason', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('expected_position', sa.Integer(), nullable=False),
    sa.Column('competitor_count', sa.Integer(), nullable=False),
    sa.Column('competitor_top1_merchant_id', sa.String(length=64), nullable=True),
    sa.Column('competitor_top1_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference_merchant_id', sa.String(length=64), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('new_price > 0', name=op.f('ck_price_history_new_price_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_history_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history'))
    )
    op.create_index('ix_price_history_product_city_created', 'price_history', ['product_id', 'city_id', 'created_at'], unique=False)
    op.create_table('product_availabilities',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('stock_count', sa.Integer(), nullable=True),
    sa.Column('preorder_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('preorder_days IS NULL OR preorder_days >= 0', name=op.f('ck_product_availabilities_preorder_days_not_negative')),
    sa.CheckConstraint('stock_count IS NULL OR stock_count >= 0', name=op.f('ck_product_availabilities_stock_count_not_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_availabilities_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_availabilities')),
    sa.UniqueConstraint('product_id', 'store_id', name=op.f('uq_product_availabilities_product_id_store_id'))
    )
    op.create_table('repricer_rules',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.Enum('beat_first', 'match_first', 'follow_second', 'target_position', 'fixed_price', 'manual', name='pricing_strategy', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('step', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('ignored_merchants', postgresql.ARRAY(sa.String(length=64)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('target_position', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_price >= min_price', name=op.f('ck_repricer_rules_max_price_not_below_min')),
    sa.CheckConstraint('min_price > 0', name=op.f('ck_repricer_rules_min_price_positive')),
    sa.CheckConstraint('step >= 1', name=op.f('ck_repricer_rules_step_positive')),
    sa.CheckConstraint('target_position IS NULL OR target_position BETWEEN 1 AND 20', name=op.f('ck_repricer_rules_target_position_in_range')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_repricer_rules_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repricer_rules')),
    sa.UniqueConstraint('product_id', 'city_id', name=op.f('uq_repricer_rules_product_id_city_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repricer_rules')
    op.drop_table('product_availabilities')
    op.drop_index('ix_price_history_product_city_created', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_products_kaspi_product_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
