"""percent limits categories margin

Revision ID: 95f28d4fad05
Revises: f7b3c1d290a4
Create Date: 2026-09-25 16:18:41.478757
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '95f28d4fad05'
down_revision: str | None = 'f7b3c1d290a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=128), nullable=True))
    op.add_column('products', sa.Column('commission_percent', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('delivery_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_index('ix_products_merchant_active', 'products', ['merchant_id', 'is_active'], unique=False)
    op.create_index('ix_products_merchant_category', 'products', ['merchant_id', 'category'], unique=False)
    op.add_column('repricer_rules', sa.Column('min_percent', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('repricer_rules', sa.Column('max_percent', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('shop_settings', sa.Column('tax_percent', sa.Numeric(precision=12, scale=2), server_default=sa.text('3'), nullable=False))
    op.add_column('shop_settings', sa.Column('commission_percent', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('shop_settings', sa.Column('delivery_cost', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###

    # Autogenerate does not compare CHECK constraints, so they are written here.
    op.create_check_constraint(
        'commission_percent_in_range', 'products',
        'commission_percent IS NULL OR commission_percent BETWEEN 0 AND 100',
    )
    op.create_check_constraint(
        'delivery_cost_not_negative', 'products', 'delivery_cost IS NULL OR delivery_cost >= 0'
    )
    op.create_check_constraint(
        'min_percent_in_range', 'repricer_rules', 'min_percent IS NULL OR min_percent BETWEEN 0 AND 90'
    )
    op.create_check_constraint(
        'max_percent_in_range', 'repricer_rules', 'max_percent IS NULL OR max_percent BETWEEN 0 AND 500'
    )
    op.create_check_constraint('tax_percent_in_range', 'shop_settings', 'tax_percent BETWEEN 0 AND 100')
    op.create_check_constraint(
        'commission_percent_in_range', 'shop_settings', 'commission_percent BETWEEN 0 AND 100'
    )
    op.create_check_constraint('delivery_cost_not_negative', 'shop_settings', 'delivery_cost >= 0')


def downgrade() -> None:
    op.drop_constraint('ck_shop_settings_delivery_cost_not_negative', 'shop_settings')
    op.drop_constraint('ck_shop_settings_commission_percent_in_range', 'shop_settings')
    op.drop_constraint('ck_shop_settings_tax_percent_in_range', 'shop_settings')
    op.drop_constraint('ck_repricer_rules_max_percent_in_range', 'repricer_rules')
    op.drop_constraint('ck_repricer_rules_min_percent_in_range', 'repricer_rules')
    op.drop_constraint('ck_products_delivery_cost_not_negative', 'products')
    op.drop_constraint('ck_products_commission_percent_in_range', 'products')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_settings', 'delivery_cost')
    op.drop_column('shop_settings', 'commission_percent')
    op.drop_column('shop_settings', 'tax_percent')
    op.drop_column('repricer_rules', 'max_percent')
    op.drop_column('repricer_rules', 'min_percent')
    op.drop_index('ix_products_merchant_category', table_name='products')
    op.drop_index('ix_products_merchant_active', table_name='products')
    op.drop_column('products', 'delivery_cost')
    op.drop_column('products', 'commission_percent')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
