"""shop settings

Revision ID: bccd44db25c0
Revises: 3f575448b862
Create Date: 2026-09-23 22:57:26.750010
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'bccd44db25c0'
down_revision: str | None = '3f575448b862'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_settings',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('merchant_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('company', sa.String(length=255), server_default='', nullable=False),
    sa.Column('merchant_rating', sa.Float(), nullable=True),
    sa.Column('proxies', postgresql.ARRAY(sa.String(length=255)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('worker_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), server_default=sa.text('300'), nullable=False),
    sa.Column('request_interval', sa.Float(), server_default=sa.text('2'), nullable=False),
    sa.Column('telegram_bot_token', sa.String(length=128), server_default='', nullable=False),
    sa.Column('telegram_chat_ids', postgresql.ARRAY(sa.String(length=32)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_shop_settings_single_row')),
    sa.CheckConstraint('interval_seconds >= 60', name=op.f('ck_shop_settings_interval_not_too_fast')),
    sa.CheckConstraint('merchant_rating IS NULL OR merchant_rating BETWEEN 0 AND 5', name=op.f('ck_shop_settings_rating_in_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_settings')
    # ### end Alembic commands ###
